theme: "jekyll-theme-cayman"
title: "Statistical Learning"
description: Repositório exclusivo para Apredizado Estatístico. Informações sobre métodos, códigos em R e Python, datasets e entre outros.
github:
  is_project_page: false
