theme: "jekyll-theme-cayman"
title: "Statistical Learning"
subtitle: "Análise de regressão"
description: Repositório exclusivo para Apredizado Estatístico. Informações sobre métodos, códigos em R e Python, datasets e entre outros.
